[Settings]
# 生成结果文件路径; 默认值: output/result.txt | Generate result file path; Default value: output/result.txt
final_file = output/user_result.txt
# 模板文件路径， 默认值: config/demo.txt | Template file path, Default value: config/demo.txt
source_file = config/user_demo.txt
# 接口协议类型偏好，优先将该类型的接口排在结果前面，可选值：ipv4、ipv6、自动、auto | Interface protocol type preference, prefer to put this type of interface in front of the result, optional values: ipv4, ipv6, 自动, auto
ipv_type_prefer = auto
# 强制认为当前网络支持IPv6，跳过检测 | Force to consider that the current network supports IPv6, skip detection
# ipv6_support = True
# 查询请求超时时长，单位秒(s)，用于控制查询接口文本链接的超时时长以及重试时长，调整此值能优化更新时间 | Query request timeout duration, unit seconds (s), used to control the timeout duration and retry duration of querying the interface text link, adjusting this value can optimize the update time
request_timeout = 2
# 单个接口测速超时时长，单位秒(s)；数值越大测速所属时间越长，能提高获取接口数量，但质量会有所下降；数值越小测速所需时间越短，能获取低延时的接口，质量较好；调整此值能优化更新时间 | Single interface speed measurement timeout duration, unit seconds (s); The larger the value, the longer the speed measurement time, which can increase the number of interfaces obtained, but the quality will decrease; The smaller the value, the shorter the speed measurement time, which can obtain interfaces with low latency and better quality; Adjusting this value can optimize the update time
sort_timeout = 2
# 开启显示接口说明信息，用于控制是否显示接口来源、分辨率、协议类型等信息，为$符号后的内容，播放软件使用该信息对接口进行描述，若部分播放器（如PotPlayer）不支持解析导致无法播放可关闭; 可选值: True, False | Enable to display interface description information, used to control whether to display interface source, resolution, protocol type and other information, the content after the $ symbol, the playback software uses this information to describe the interface, if some players (such as PotPlayer) do not support parsing and cannot play, you can turn it off; Optional values: True, False
open_url_info = True
# CDN代理加速地址，用于订阅源、频道图标等资源的加速访问 | CDN proxy acceleration address, used for accelerated access to subscription sources, channel icons and other resources
cdn_url = https://gh-proxy.com/
# 接口最小速率（单位M/s），需要开启 open_filter_speed 才能生效 | Minimum rate of the interface (unit M/s), need to enable open_filter_speed to take effect
min_speed = 0.3